server:
   max-http-header-size: 10000
  # port: 8505
   port: 8509
   servlet:
    context-path: /smt-app
   
jdb:
  orm:
    filepath: jdb-orm.conf.xml
    data-source-close-method-name: close
    
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://192.168.1.200:1433;DatabaseName=SmartOne2_VC
      username: sa 
      password: 123123
  application:
     #name: smt-app
     name: smt-app1

# 指定该服务要注册进指定url的服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.200:8501/eureka/

smt:
  parent:
    code:
      filter:
        cors:
          access-control-allow-methods: GET,POST,PUT,DELETE
          access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, _log, token
          access-control-max-age: 1800
  app:
    fileUploudKeySeparator: .
    sizes: 10
    fileUploudServerAddress: D:\\workspace\\files
    excelExportEncryption: true